### ISSUE TITLE
OSC Property Sender - Unity to Ableton 

### ISSUE THREAD

**Issue by Bramichou** [keijiro/OscJack#17]
Hello ! 

First, thanks for all what you do for us ! Amazing work and amazing guy :) 

I have a question about how works the OSC Property Sender, i have at this moment setup the component with right port, i dragged my gameobject in the Data Source but i want to access to a variable of the script which is a `public float` updated each frame... How am i suppose to do because i have only `tag` and `name` as property of my component which is a script that i attached to my gamebject that i dragged.

Thank you ! 👍

**Comment by keijiro** [comment]
I guess your script only has a public float variable. The OSC Property Sender class requires a public property.

**Comment by Bramichou** [comment]
Thank you for answering so quickly, 

My script got a lot of public variable, and i want to send one of them which is a value which is updated each frame between 0 and 1. So how am i suppose to do to set a public property, to get this variable to send it in OSC ?

**Comment by Bramichou** [comment]
Ok i solved this by adding a getter ! 

But now have a new question about how am i suppose to get this value to bind it to a filter in ableton ? :)

**Comment by keijiro** [comment]
I'm closing this issue now because the issue became irrelevant to Unity/OSCJack. I think you can use "OSC TouchOSC" device in the Connection Kit for the purpose, I have never tried it yet though. I'd recommend asking Ableton forum for further questions. I hope you'll find a good solution for it.

https://www.ableton.com/en/packs/connection-kit/
